# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from functions import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(873, 500)
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 851, 112))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        
        self.logo_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.logo_label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.logo_label.setText("")
        self.logo_label.setPixmap(QtGui.QPixmap("../home/ilias/ensomatomena/testing/eceS.png"))
        self.logo_label.setObjectName("logo_label")
        
        self.horizontalLayout.addWidget(self.logo_label)
        self.welcome_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.welcome_label.setFont(font)
        self.welcome_label.setIndent(100)
        self.welcome_label.setObjectName("welcome_label")
        
        self.horizontalLayout.addWidget(self.welcome_label)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 120, 831, 311))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 30, 791, 281))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        
        #########################################################################################################
        ##  My Buttons STARTS ##
        #########################################################################################################

        #check google 
        self.check_google_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.check_google_btn.setMaximumSize(QtCore.QSize(200, 100))
        self.check_google_btn.setObjectName("check_google_btn")
        self.gridLayout.addWidget(self.check_google_btn, 0, 0, 1, 1)
        self.check_google_btn.clicked.connect(self.show_popupCheckGoogle)
        self.check_google_btn.setToolTip('Ping google.com, see if it\'s online')

        #launch terminal
        self.launch_a_terminal_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.launch_a_terminal_btn.setMaximumSize(QtCore.QSize(200, 100))
        self.launch_a_terminal_btn.setObjectName("launch_a_terminal_btn")
        self.gridLayout.addWidget(self.launch_a_terminal_btn, 1, 1, 1, 1)
        self.launch_a_terminal_btn.clicked.connect(blaunch_a_terminal)
        self.launch_a_terminal_btn.setToolTip('Launch a terminal, tweak the system with responsibility!!')

        #first n fibonacci
        self.n_fibo_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.n_fibo_btn.setMaximumSize(QtCore.QSize(200, 100))
        self.n_fibo_btn.setObjectName("n_fibo_btn")
        self.gridLayout.addWidget(self.n_fibo_btn, 1, 0, 1, 1)
        self.n_fibo_btn.setToolTip('Show the first N numbers of fibonacci sequence')
        #thread1=threading.Thread(target=self.show_popupFibo)

        self.n_fibo_btn.clicked.connect(self.show_popupFibo)
        #thread1.join()  

        #sys os info
        self.sys_os_info_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.sys_os_info_btn.setMaximumSize(QtCore.QSize(200, 100))
        self.sys_os_info_btn.setObjectName("sys_os_info_btn")
        self.gridLayout.addWidget(self.sys_os_info_btn, 1, 2, 1, 1)
        self.sys_os_info_btn.clicked.connect(self.show_popupOS)
        self.sys_os_info_btn.setToolTip('See what OS i am running on!')
        
        #visit youtube.com
        self.visit_youtube_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.visit_youtube_btn.setMaximumSize(QtCore.QSize(200, 100))
        self.visit_youtube_btn.setObjectName("visit_youtube_btn")
        self.gridLayout.addWidget(self.visit_youtube_btn, 0, 1, 1, 1)
        self.visit_youtube_btn.clicked.connect(bvisit_youtube)
        self.visit_youtube_btn.setToolTip('Visit youtube.com through a web browser')

        #sys ip
        self.sys_ip_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.sys_ip_btn.setMaximumSize(QtCore.QSize(200, 100))
        self.sys_ip_btn.setObjectName("sys_ip_btn")
        self.gridLayout.addWidget(self.sys_ip_btn, 0, 2, 1, 1)
        self.sys_ip_btn.setToolTip('Show system\'s local IPv4')
        self.sys_ip_btn.clicked.connect(self.show_popupIP)
        self.gridLayout.addWidget(self.sys_ip_btn, 0, 2, 1, 1)

        #exit button
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(700, 440, 80, 26))
        self.pushButton.setObjectName("pushButton")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 873, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        #########################################################################################################
        ##  My Buttons ENDS ##
        #########################################################################################################

        
        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.welcome_label.setText(_translate("MainWindow", "Welcome to my Embedded Systems Project!"))
        self.check_google_btn.setText(_translate("MainWindow", "Check google.com "))
        self.launch_a_terminal_btn.setText(_translate("MainWindow", "Launch a Terminal"))
        self.n_fibo_btn.setText(_translate("MainWindow", "First N of Fibonacci Sequence"))
        self.sys_os_info_btn.setText(_translate("MainWindow", "OS specs"))
        self.visit_youtube_btn.setText(_translate("MainWindow", "Visit youtube.com "))
        self.sys_ip_btn.setText(_translate("MainWindow", "What\'s my local ip"))
        self.pushButton.setText(_translate("MainWindow", "EXIT"))

    def show_popupIP(self):
        msg = QMessageBox()
        msg.setWindowTitle("Your IP is:")
        ip=getIP()
        msg.setText(ip)
        msg.setStyleSheet("QLabel{min-width:300 px; font-size: 24px;} QPushButton{ width:350px; font-size: 18px; }");
        x = msg.exec_()

    def show_popupOS(self):
        msg = QMessageBox()
        msg.setWindowTitle("What OS am i running on:")
        info=sys_os_info()
        msg.setText(info)
        msg.setStyleSheet("QLabel{min-width:500 px; font-size: 24px;} QPushButton{ width:350px; font-size: 18px; }");
        x = msg.exec_()
    
    ##Fibo
    def show_popupFibo(self):
        msg = QMessageBox()
        msg.setWindowTitle("First N fibonacci")
        arr=generate_fibonacci(10)
        msg.setText(arr)
        msg.setStyleSheet("QLabel{min-width:400 px; font-size: 20px;} QPushButton{ width:350px; font-size: 18px; }");
        x = msg.exec_()
 
    ##Fibo ENDS

    def show_popupCheckGoogle(self):
        msg = QMessageBox()
        msg.setWindowTitle("Pinging 4 packets to google.com, please wait!")
        check=ping_check()
        msg.setText(check)
        msg.setStyleSheet("QLabel{min-width:500 px; font-size: 24px;} QPushButton{ width:350px; font-size: 18px; }");
        x = msg.exec_()  

#########################################################################################################
##  My Buttons Functions STARTS ##
#########################################################################################################

def blaunch_a_terminal():
    launch_terminal()

def bvisit_youtube():
    visit_page()

#########################################################################################################
##  My Buttons Functions ENDS ##
#########################################################################################################


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
